# Generated by Django 4.2.4 on 2023-09-03 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default='09:00', verbose_name='время рассылки')),
                ('period', models.CharField(choices=[('D', 'Каждый день'), ('W', 'Каждую неделю'), ('M', 'Каждый месяц')], max_length=30, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('active', 'Запущена'), ('closed', 'Завершена')], default='created', max_length=10, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='почта'),
        ),
        migrations.CreateModel(
            name='TextMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_mail.mailsettings', verbose_name='письмо')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_mail.client', verbose_name='клиент')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_mail.mailsettings', verbose_name='настройка')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.CreateModel(
            name='LogMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('status', models.BooleanField(default=True, verbose_name='статус последней попытки')),
                ('response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_mail.mailsettings', verbose_name='настройка')),
            ],
            options={
                'verbose_name': 'Логи сообщения',
                'verbose_name_plural': 'Логи сообщения',
            },
        ),
    ]
