# Generated by Django 4.2.4 on 2023-09-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0003_alter_client_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('active', 'Запущена'), ('closed', 'Завершена')], default='created', max_length=10, verbose_name='статус рассылки'),
        ),
    ]
