# Generated by Django 4.2.4 on 2023-08-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0003_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
            },
        ),
    ]
