# Generated by Django 4.2.4 on 2023-09-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0003_mailsettings_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmail',
            name='mail',
        ),
    ]
