# Generated by Django 4.2.4 on 2023-08-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0004_textmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_last_try', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('status_try', models.CharField(max_length=10, verbose_name='статус последней попытки')),
                ('answer_mail_server', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Логи сообщения',
            },
        ),
    ]
