# Generated by Django 4.2.4 on 2023-08-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0004_textmail_logsmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='interval',
            field=models.CharField(choices=[('D', 'Каждый день'), ('W', 'Каждую неделю'), ('M', 'Каждый месяц')], verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='time',
            field=models.TimeField(default='09:00', verbose_name='время рассылки'),
        ),
    ]
