# Generated by Django 4.2.4 on 2023-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0005_textmail_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmail',
            name='body',
            field=models.TextField(verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='textmail',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='тема'),
        ),
    ]
