# Generated by Django 4.2.4 on 2023-09-03 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0005_rename_logsmail_logmail_rename_mail_mailsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailinClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_mail.client', verbose_name='клиент')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_mail.mailsettings', verbose_name='настройка')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
