# Generated by Django 4.2.4 on 2023-09-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0006_mailinclient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailinClient',
            new_name='MailingClient',
        ),
    ]
