# Generated by Django 4.2.4 on 2023-09-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0007_remove_mailsettings_time_mailsettings_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='send_mail.mailsettings', verbose_name='настройки'),
        ),
    ]
