# Generated by Django 4.2.4 on 2023-09-19 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0008_client_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='textmail',
            name='settings',
        ),
    ]
