# Generated by Django 4.2.4 on 2023-09-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0009_remove_client_settings_remove_textmail_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingclient',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailsettings',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.RemoveField(
            model_name='mailingclient',
            name='client',
        ),
        migrations.AddField(
            model_name='mailingclient',
            name='clients',
            field=models.ManyToManyField(to='send_mail.client', verbose_name='клиент'),
        ),
    ]
