# Generated by Django 4.2.4 on 2023-09-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0010_alter_mailingclient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingclient',
            name='clients',
        ),
        migrations.AddField(
            model_name='mailingclient',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='send_mail.client', verbose_name='клиент'),
        ),
    ]
