# Generated by Django 4.2.4 on 2023-09-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0013_remove_mailingclient_clients_mailingclient_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='send_mail.mailingclient', verbose_name='рассылка'),
        ),
    ]
