# Generated by Django 4.2.4 on 2023-09-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0014_client_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingclient',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='send_mail.mailsettings', verbose_name='настройка'),
        ),
    ]
