# Generated by Django 4.2.4 on 2023-09-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0015_alter_mailingclient_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingclient',
            name='clients',
        ),
        migrations.AddField(
            model_name='mailingclient',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, to='send_mail.client', verbose_name='клиент'),
        ),
    ]
