# Generated by Django 4.2.4 on 2023-09-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0016_remove_mailingclient_clients_mailingclient_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingclient',
            name='clients',
            field=models.ManyToManyField(to='send_mail.client', verbose_name='клиент'),
        ),
    ]
