# Generated by Django 4.2.4 on 2023-09-26 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_mail', '0017_alter_mailingclient_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='mailingclient',
            name='clients',
            field=models.ManyToManyField(to='send_mail.client', verbose_name='клиенты'),
        ),
    ]
