# Generated by Django 4.2.4 on 2023-09-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0019_mailingclient_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='users',
        ),
    ]
